apiVersion: apps/v1
kind: Deployment

metadata:
  name: kaniko-test

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: kaniko-test

  template:
    metadata:
      labels:
        app: kaniko-test

    spec:
      terminationGracePeriodSeconds: 10

      containers:
        - name: kaniko-test
          image: us-central1-docker.pkg.dev/clgcporg193-p001/kaniko-test/kaniko-test:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
