apiVersion: apps/v1
kind: Deployment

metadata:
  name: kaniko-test

spec:
  replicas: 1

  # For this PoC, terminate the old pod before
  # starting the new one.
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: kaniko-test

  template:
    metadata:
      labels:
        app: kaniko-test

    spec:
      terminationGracePeriodSeconds: 10

      containers:
        - name: kaniko-test

          image: us-central1-docker.pkg.dev/clgcporg193-p001/kaniko-test/kaniko-test:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8080
